### ISSUE TITLE
Install Drupal 9 with PostgreSQL

### ISSUE THREAD

**Issue by roman-yakimkin** [docksal/boilerplate-drupal9#3]
Explain please, how to install this version of Drupal 9 with PostgreSQL instead of MySQL? I tried to use this manual, but it refused to install. 
https://github.com/docksal/docksal/issues/193#issuecomment-376343111

**Comment by shelane** [comment]
Drupal 9 requires PostgreSQL 10.0 or higher with the pg_trgm extension (see status of PostgreSQL support in Drupal 9). I think the Docksal version is still 9.6.

**Comment by batigolix** [comment]
If you add the pgsql service you get the right postgres version for Drupal 9 https://docs.docksal.io/service/db/options/#postresql-config

**Comment by shelane** [comment]
Yes, the stack service was changed to Postgres 10.14 in the [1.15.0 release](https://github.com/docksal/docksal/releases/tag/v1.15.0) in Nov 2020.
